---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: providers-sa
  namespace: crossplane-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: providers-cr
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: providers-cr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: providers-cr
subjects:
  - kind: ServiceAccount
    name: providers-sa
    namespace: crossplane-system
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: providers-cc
spec:
  serviceAccountName: providers-sa
