---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: apache-example-mr
spec:
  providerConfigRef:
    name: helm-provider-pc
  forProvider:
    chart:
      repository: https://charts.bitnami.com/bitnami
      name: apache
      version: 11.2.21
    namespace: workshop-provider-helm
    set:
      - name: param1
        value: value1
    values:
      service:
        type: ClusterIP
