---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xkomodorchartsets.xrd.komodor.com
spec:
  group: xrd.komodor.com
  names:
    kind: XKomodorChartSet
    plural: xkomodorchartsets
  claimNames:
    kind: KomodorChartSet
    plural: komodorchartsets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hdashboardVer:
                  type: string
                komoplaneVer:
                  type: string
              required:
                - hdashboardVer
                - komoplaneVer
