---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmegas.xrd.komodor.com
spec:
  group: xrd.komodor.com
  names:
    kind: XMega
    plural: xmegas
  claimNames:
    kind: Mega
    plural: megas
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
              required:
                - namespace
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mega-composition
spec:
  compositeTypeRef:
    apiVersion: xrd.komodor.com/v1alpha1
    kind: XMega
  resources:
    - name: provider-k8s-resource
      base:
        apiVersion: kubernetes.crossplane.io/v1alpha2
        kind: Object
        spec:
          providerConfigRef:
            name: k8s-provider-pc
          forProvider:
            manifest:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: "" # will be set via patches
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.manifest.metadata.name

    - name: provider-helm-release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          providerConfigRef:
            name: helm-provider-pc
          forProvider:
            chart:
              repository: https://charts.bitnami.com/bitnami
              name: apache
              version: 11.2.21
            namespace: "default"  # This will be dynamically overwritten
            skipCreateNamespace: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.namespace
          toFieldPath: spec.forProvider.namespace

    - name: composition-of-compositions
      base:
        apiVersion: xrd.komodor.com/v1alpha1
        kind: XKomodorChartSet
        metadata:
          namespace: ""
        spec:
          hdashboardVer: 0.1.10
          komoplaneVer: 0.1.5
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.namespace
          toFieldPath: metadata.namespace
