# .goreleaser.yml
# Build customization
builds:
  - id: unix
    main: ./main.go
    binary: komoplane
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
  - id: Win
    main: ./main.go
    binary: komoplane
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - id: komoplane
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
