# kind delete cluster && kind create cluster && helm upgrade --install crossplane crossplane/crossplane -n crossplane-system --create-namespace # --set provider.packages={xpkg.upbound.io/crossplane-contrib/provider-helm:v0.15.0}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-helm-sa
#  namespace: crossplane-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: provider-helm-cr
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch", "create", "delete", "patch", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-helm-cr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provider-helm-cr
subjects:
  - kind: ServiceAccount
    name: provider-helm-sa
    namespace: crossplane-system

---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-helm-cc
spec:
  serviceAccountName: provider-helm-sa




---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.15.0
  controllerConfigRef:
    name: provider-helm-cc

---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: helm-provider
spec:
  credentials:
    source: InjectedIdentity