apiVersion: v2
type: application

name: komoplane
description: Komodor tool to visualize Crossplane
icon: https://raw.githubusercontent.com/komodorio/komoplane/main/pkg/frontend/src/assets/logo.svg
maintainers:
  - name: komodorio
    email: support@komodor.com
    url: https://github.com/komodorio

version: 0.1.7
appVersion: "0.2.0"
