name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:

  image:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: komodorio/komoplane

      - name: Login to DockerHub
        uses: docker/login-action@v2
        if: github.event_name == 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v4
        if: github.event_name == 'pull_request'
        with:
          context: .
          push: ${{ github.event_name == 'pull_request' }}
          tags: komodorio/komoplane:unstable
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VER=0.0.0
